/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { ApiKeyDTO } from './models/ApiKeyDTO';
export type { ApiKeyRequest } from './models/ApiKeyRequest';
export { App } from './models/App';
export type { Base64File } from './models/Base64File';
export type { BinaryFile } from './models/BinaryFile';
export { Button } from './models/Button';
export type { CallData } from './models/CallData';
export type { CallsAppChannelConfig } from './models/CallsAppChannelConfig';
export type { CallsAppConfig } from './models/CallsAppConfig';
export { Channel } from './models/Channel';
export type { ChannelCategory } from './models/ChannelCategory';
export type { ChannelCountry } from './models/ChannelCountry';
export type { ChannelListResult } from './models/ChannelListResult';
export type { ChannelMessage } from './models/ChannelMessage';
export type { ChannelPagination } from './models/ChannelPagination';
export type { ChannelPublicInfo } from './models/ChannelPublicInfo';
export type { ChannelSearchByText } from './models/ChannelSearchByText';
export type { ChannelSearchByView } from './models/ChannelSearchByView';
export type { ChannelView } from './models/ChannelView';
export type { ChatArchiveEvent } from './models/ChatArchiveEvent';
export type { ChatPictureResponse } from './models/ChatPictureResponse';
export type { ChatRequest } from './models/ChatRequest';
export type { ChatSummary } from './models/ChatSummary';
export { ChatWootAppConfig } from './models/ChatWootAppConfig';
export type { ChatWootCommandsConfig } from './models/ChatWootCommandsConfig';
export { ChatWootConversationsConfig } from './models/ChatWootConversationsConfig';
export type { ClientSessionConfig } from './models/ClientSessionConfig';
export type { Contact } from './models/Contact';
export type { ContactRequest } from './models/ContactRequest';
export type { ContactUpdateBody } from './models/ContactUpdateBody';
export type { CountResponse } from './models/CountResponse';
export type { CreateChannelRequest } from './models/CreateChannelRequest';
export type { CreateGroupRequest } from './models/CreateGroupRequest';
export type { CustomHeader } from './models/CustomHeader';
export type { DeleteStatusRequest } from './models/DeleteStatusRequest';
export type { DescriptionRequest } from './models/DescriptionRequest';
export type { EditMessageRequest } from './models/EditMessageRequest';
export type { EnginePayload } from './models/EnginePayload';
export type { EventLocation } from './models/EventLocation';
export type { EventMessage } from './models/EventMessage';
export type { EventMessageRequest } from './models/EventMessageRequest';
export { EventResponse } from './models/EventResponse';
export { EventResponsePayload } from './models/EventResponsePayload';
export type { FileContent } from './models/FileContent';
export type { FileURL } from './models/FileURL';
export type { GetChatsOverviewParams } from './models/GetChatsOverviewParams';
export type { GowsConfig } from './models/GowsConfig';
export type { GowsStorageConfig } from './models/GowsStorageConfig';
export type { GroupId } from './models/GroupId';
export type { GroupInfo } from './models/GroupInfo';
export { GroupParticipant } from './models/GroupParticipant';
export type { GroupV2JoinEvent } from './models/GroupV2JoinEvent';
export type { GroupV2LeaveEvent } from './models/GroupV2LeaveEvent';
export { GroupV2ParticipantsEvent } from './models/GroupV2ParticipantsEvent';
export type { GroupV2UpdateEvent } from './models/GroupV2UpdateEvent';
export type { HmacConfiguration } from './models/HmacConfiguration';
export type { IgnoreConfig } from './models/IgnoreConfig';
export type { ImageStatus } from './models/ImageStatus';
export type { JoinGroupRequest } from './models/JoinGroupRequest';
export type { JoinGroupResponse } from './models/JoinGroupResponse';
export type { Label } from './models/Label';
export type { LabelBody } from './models/LabelBody';
export type { LabelChatAssociation } from './models/LabelChatAssociation';
export type { LabelID } from './models/LabelID';
export type { LidToPhoneNumber } from './models/LidToPhoneNumber';
export type { LinkPreviewData } from './models/LinkPreviewData';
export type { MeInfo } from './models/MeInfo';
export type { MessageButtonReply } from './models/MessageButtonReply';
export type { MessageContactVcardRequest } from './models/MessageContactVcardRequest';
export type { MessageDestination } from './models/MessageDestination';
export type { MessageFileRequest } from './models/MessageFileRequest';
export type { MessageForwardRequest } from './models/MessageForwardRequest';
export type { MessageImageRequest } from './models/MessageImageRequest';
export type { MessageLinkCustomPreviewRequest } from './models/MessageLinkCustomPreviewRequest';
export type { MessageLinkPreviewRequest } from './models/MessageLinkPreviewRequest';
export type { MessageLocationRequest } from './models/MessageLocationRequest';
export type { MessagePoll } from './models/MessagePoll';
export type { MessagePollRequest } from './models/MessagePollRequest';
export type { MessagePollVoteRequest } from './models/MessagePollVoteRequest';
export type { MessageReactionRequest } from './models/MessageReactionRequest';
export type { MessageReplyRequest } from './models/MessageReplyRequest';
export type { MessageStarRequest } from './models/MessageStarRequest';
export type { MessageTextRequest } from './models/MessageTextRequest';
export type { MessageVideoRequest } from './models/MessageVideoRequest';
export type { MessageVoiceRequest } from './models/MessageVoiceRequest';
export type { MyProfile } from './models/MyProfile';
export type { NewMessageIDResponse } from './models/NewMessageIDResponse';
export type { NowebConfig } from './models/NowebConfig';
export type { NowebStoreConfig } from './models/NowebStoreConfig';
export type { OverviewBodyRequest } from './models/OverviewBodyRequest';
export type { OverviewFilter } from './models/OverviewFilter';
export type { Participant } from './models/Participant';
export type { ParticipantsRequest } from './models/ParticipantsRequest';
export type { PingResponse } from './models/PingResponse';
export type { PinMessageRequest } from './models/PinMessageRequest';
export type { PollVote } from './models/PollVote';
export type { PollVotePayload } from './models/PollVotePayload';
export type { ProfileNameRequest } from './models/ProfileNameRequest';
export type { ProfilePictureRequest } from './models/ProfilePictureRequest';
export type { ProfileStatusRequest } from './models/ProfileStatusRequest';
export type { ProxyConfig } from './models/ProxyConfig';
export type { QRCodeValue } from './models/QRCodeValue';
export type { ReadChatMessagesResponse } from './models/ReadChatMessagesResponse';
export type { RejectCallRequest } from './models/RejectCallRequest';
export type { RemoteFile } from './models/RemoteFile';
export type { ReplyToMessage } from './models/ReplyToMessage';
export type { RequestCodeRequest } from './models/RequestCodeRequest';
export type { Result } from './models/Result';
export { RetriesConfiguration } from './models/RetriesConfiguration';
export type { Row } from './models/Row';
export type { S3MediaData } from './models/S3MediaData';
export type { Section } from './models/Section';
export type { SendButtonsRequest } from './models/SendButtonsRequest';
export type { SendListMessage } from './models/SendListMessage';
export type { SendListRequest } from './models/SendListRequest';
export type { SendSeenRequest } from './models/SendSeenRequest';
export type { ServerStatusResponse } from './models/ServerStatusResponse';
export type { SessionConfig } from './models/SessionConfig';
export type { SessionCreateRequest } from './models/SessionCreateRequest';
export { SessionDTO } from './models/SessionDTO';
export { SessionInfo } from './models/SessionInfo';
export type { SessionLogoutDeprecatedRequest } from './models/SessionLogoutDeprecatedRequest';
export type { SessionStartDeprecatedRequest } from './models/SessionStartDeprecatedRequest';
export { SessionStatusPoint } from './models/SessionStatusPoint';
export type { SessionStopDeprecatedRequest } from './models/SessionStopDeprecatedRequest';
export type { SessionUpdateRequest } from './models/SessionUpdateRequest';
export type { SetLabelsRequest } from './models/SetLabelsRequest';
export type { SettingsSecurityChangeInfo } from './models/SettingsSecurityChangeInfo';
export type { StopRequest } from './models/StopRequest';
export type { StopResponse } from './models/StopResponse';
export type { SubjectRequest } from './models/SubjectRequest';
export type { TextStatus } from './models/TextStatus';
export type { VCardContact } from './models/VCardContact';
export type { VideoBinaryFile } from './models/VideoBinaryFile';
export type { VideoFileDTO } from './models/VideoFileDTO';
export type { VideoRemoteFile } from './models/VideoRemoteFile';
export type { VideoStatus } from './models/VideoStatus';
export type { VoiceBinaryFile } from './models/VoiceBinaryFile';
export type { VoiceFileDTO } from './models/VoiceFileDTO';
export type { VoiceRemoteFile } from './models/VoiceRemoteFile';
export type { VoiceStatus } from './models/VoiceStatus';
export type { WAHAChatPresences } from './models/WAHAChatPresences';
export type { WAHAEnvironment } from './models/WAHAEnvironment';
export { WAHAPresenceData } from './models/WAHAPresenceData';
export { WAHASessionPresence } from './models/WAHASessionPresence';
export { WAHAWebhookCallAccepted } from './models/WAHAWebhookCallAccepted';
export { WAHAWebhookCallReceived } from './models/WAHAWebhookCallReceived';
export { WAHAWebhookCallRejected } from './models/WAHAWebhookCallRejected';
export { WAHAWebhookChatArchive } from './models/WAHAWebhookChatArchive';
export { WAHAWebhookEngineEvent } from './models/WAHAWebhookEngineEvent';
export { WAHAWebhookEventResponse } from './models/WAHAWebhookEventResponse';
export { WAHAWebhookEventResponseFailed } from './models/WAHAWebhookEventResponseFailed';
export { WAHAWebhookGroupJoin } from './models/WAHAWebhookGroupJoin';
export { WAHAWebhookGroupLeave } from './models/WAHAWebhookGroupLeave';
export { WAHAWebhookLabelChatAdded } from './models/WAHAWebhookLabelChatAdded';
export { WAHAWebhookLabelChatDeleted } from './models/WAHAWebhookLabelChatDeleted';
export { WAHAWebhookLabelDeleted } from './models/WAHAWebhookLabelDeleted';
export { WAHAWebhookLabelUpsert } from './models/WAHAWebhookLabelUpsert';
export { WAHAWebhookMessage } from './models/WAHAWebhookMessage';
export { WAHAWebhookMessageAck } from './models/WAHAWebhookMessageAck';
export { WAHAWebhookMessageAckGroup } from './models/WAHAWebhookMessageAckGroup';
export { WAHAWebhookMessageAny } from './models/WAHAWebhookMessageAny';
export { WAHAWebhookMessageEdited } from './models/WAHAWebhookMessageEdited';
export { WAHAWebhookMessageReaction } from './models/WAHAWebhookMessageReaction';
export { WAHAWebhookMessageRevoked } from './models/WAHAWebhookMessageRevoked';
export { WAHAWebhookPollVote } from './models/WAHAWebhookPollVote';
export { WAHAWebhookPollVoteFailed } from './models/WAHAWebhookPollVoteFailed';
export { WAHAWebhookPresenceUpdate } from './models/WAHAWebhookPresenceUpdate';
export { WAHAWebhookSessionStatus } from './models/WAHAWebhookSessionStatus';
export { WAHAWebhookStateChange } from './models/WAHAWebhookStateChange';
export type { WALocation } from './models/WALocation';
export type { WAMedia } from './models/WAMedia';
export { WAMessage } from './models/WAMessage';
export { WAMessageAckBody } from './models/WAMessageAckBody';
export { WAMessageEditedBody } from './models/WAMessageEditedBody';
export { WAMessageReaction } from './models/WAMessageReaction';
export type { WAMessageRevokedBody } from './models/WAMessageRevokedBody';
export type { WANumberExistResult } from './models/WANumberExistResult';
export type { WAReaction } from './models/WAReaction';
export { WASessionStatusBody } from './models/WASessionStatusBody';
export type { WebhookConfig } from './models/WebhookConfig';
export { WebhookGroupV2Join } from './models/WebhookGroupV2Join';
export { WebhookGroupV2Leave } from './models/WebhookGroupV2Leave';
export { WebhookGroupV2Participants } from './models/WebhookGroupV2Participants';
export { WebhookGroupV2Update } from './models/WebhookGroupV2Update';
export type { WebjsConfig } from './models/WebjsConfig';
export type { WorkerInfo } from './models/WorkerInfo';

export { ApiKeysService } from './services/ApiKeysService';
export { AppsService } from './services/AppsService';
export { CallsService } from './services/CallsService';
export { ChannelsService } from './services/ChannelsService';
export { ChatsService } from './services/ChatsService';
export { ChattingService } from './services/ChattingService';
export { ContactsService } from './services/ContactsService';
export { EventsService } from './services/EventsService';
export { GroupsService } from './services/GroupsService';
export { LabelsService } from './services/LabelsService';
export { MediaService } from './services/MediaService';
export { ObservabilityService } from './services/ObservabilityService';
export { PairingService } from './services/PairingService';
export { PresenceService } from './services/PresenceService';
export { ProfileService } from './services/ProfileService';
export { SessionsService } from './services/SessionsService';
export { StatusService } from './services/StatusService';
